// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fafywhojwgfajsssvkux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZnl3aG9qd2dmYWpzc3N2a3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTg5MzMsImV4cCI6MjA2NTM5NDkzM30.jpxHbsT-12UtAjwB7-PCnQSm4PEtWcQIH4D85b3Ep4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'x-my-custom-header': 'lovable-joker-club',
    },
  },
});